import fs from 'node:fs/promises';
import path from 'node:path';

import { config } from '../config.js';

export const BASELINE_GITIGNORE_LINES = [
  '.DS_Store',
  '._*',
  '.Spotlight-V100',
  '.Trashes',
  '.opskit/settings.local.json',
  'PROJECT_CONTEXT.local.md',
];

const JUNK_SEGMENTS = new Set(['.Spotlight-V100', '.Trashes']);

function normalizePath(value) {
  return value.replace(/\\/g, '/');
}

function splitSegments(value) {
  return normalizePath(value).split('/').filter(Boolean);
}

function isIgnoredSegment(segment) {
  return (
    segment === '.DS_Store' ||
    segment.startsWith('._') ||
    JUNK_SEGMENTS.has(segment)
  );
}

function buildDeployTargetSummary() {
  if (!config.railwayDeployEnabled) {
    return 'Not configured for automatic deploy yet.';
  }

  return [
    `Railway project: ${config.railwayProjectId || 'unset'}`,
    `Railway environment: ${config.railwayEnvironmentId || 'unset'}`,
    `Railway service: ${config.railwayServiceId || 'unset'}`,
  ].join('\n');
}

function buildProjectContext(task) {
  return `# Project Context

## Objective

${task.title}

## Source Task

${task.description}

## Delivery Notes

- Generated by LocalClaw in controlled workspace mode
- Task ID: ${task.id}
- Priority: ${task.priority}
- Source: ${task.source}

## Deployment Target

${buildDeployTargetSummary()}

## Local Overrides

Use \`PROJECT_CONTEXT.local.md\` for machine-specific notes that must not be committed.
`;
}

function buildProjectRules() {
  return `# Project Rules

## Engineering

- Keep changes small, explicit, and readable.
- Prefer deterministic behavior over clever abstractions.
- Do not commit secrets, tokens, or local-only credentials.

## Testing

- Add or update a runnable verification path for meaningful changes.
- Fail fast when required runtime configuration is missing.
- Keep logs useful enough for a human operator to diagnose the latest step.

## Git Hygiene

- Do not commit OS junk such as \`.DS_Store\` or \`._*\`.
- Keep ignored local overrides in \`PROJECT_CONTEXT.local.md\` and \`.opskit/settings.local.json\`.

## Deployment

- Deployment remains approval-gated.
- Treat external actions as blocked until the operator confirms them.
`;
}

function buildOpskitReadme() {
  return `# Opskit

This folder is the committed repo contract for LocalClaw-generated projects.

- \`settings.json\`: committed execution defaults
- \`settings.local.json\`: local-only overrides
- \`commands/\`: reusable task command specs
- \`rules/\`: modular project rules
- \`skills/\`: reusable workflow instructions
- \`agents/\`: role-specific operating notes
`;
}

function buildOpskitSettings(task) {
  return `${JSON.stringify(
    {
      version: 1,
      generatedBy: 'localclaw',
      projectTaskId: task.id,
      projectTaskTitle: task.title,
      deploy: {
        provider: config.railwayDeployEnabled ? 'railway' : 'manual',
        approvalRequired: true,
      },
      hygiene: {
        ignoreOsJunk: true,
        enforceRepoContract: true,
      },
    },
    null,
    2
  )}\n`;
}

function buildOpskitLocalSettings() {
  return `${JSON.stringify(
    {
      notes: 'Local-only overrides belong here.',
    },
    null,
    2
  )}\n`;
}

function buildCommandDoc(title, purpose) {
  return `# ${title}

## Purpose

${purpose}

## Expected Output

- concise result summary
- referenced files or commands
- clear follow-up action if blocked
`;
}

function buildRuleDoc(title, rules) {
  return `# ${title}

${rules.map((rule) => `- ${rule}`).join('\n')}
`;
}

function buildSkillDoc(title, workflow) {
  return `# ${title}

## Workflow

${workflow.map((step, index) => `${index + 1}. ${step}`).join('\n')}
`;
}

function buildAgentDoc(title, responsibilities) {
  return `# ${title}

${responsibilities.map((item) => `- ${item}`).join('\n')}
`;
}

function getRepoContractFiles(task) {
  return [
    {
      relativePath: 'PROJECT_CONTEXT.md',
      content: buildProjectContext(task),
    },
    {
      relativePath: 'PROJECT_CONTEXT.local.md',
      content: '# Local Project Context\n\nAdd local-only notes here.\n',
    },
    {
      relativePath: 'PROJECT_RULES.md',
      content: buildProjectRules(),
    },
    {
      relativePath: '.opskit/README.md',
      content: buildOpskitReadme(),
    },
    {
      relativePath: '.opskit/settings.json',
      content: buildOpskitSettings(task),
    },
    {
      relativePath: '.opskit/settings.local.json',
      content: buildOpskitLocalSettings(),
    },
    {
      relativePath: '.opskit/commands/review.md',
      content: buildCommandDoc('Review', 'Review the current change set before approval or deploy.'),
    },
    {
      relativePath: '.opskit/commands/fix-issue.md',
      content: buildCommandDoc('Fix Issue', 'Diagnose and fix a reproducible project issue with verification.'),
    },
    {
      relativePath: '.opskit/commands/deploy.md',
      content: buildCommandDoc('Deploy', 'Prepare a deploy-ready summary and verify approval prerequisites.'),
    },
    {
      relativePath: '.opskit/rules/code-style.md',
      content: buildRuleDoc('Code Style', [
        'Prefer small modules and readable names.',
        'Keep comments short and only where they remove ambiguity.',
        'Avoid hidden behavior and implicit side effects.',
      ]),
    },
    {
      relativePath: '.opskit/rules/testing.md',
      content: buildRuleDoc('Testing', [
        'Add a runnable verification path for important behavior.',
        'Prefer fast local checks before external actions.',
        'Capture failure output clearly when a test cannot pass.',
      ]),
    },
    {
      relativePath: '.opskit/rules/api.md',
      content: buildRuleDoc('API', [
        'Keep interfaces explicit and stable.',
        'Validate required inputs before doing external work.',
        'Return actionable error messages for operator-visible failures.',
      ]),
    },
    {
      relativePath: '.opskit/skills/workspace-hygiene/SKILL.md',
      content: buildSkillDoc('Workspace Hygiene', [
        'Ensure .gitignore contains the baseline LocalClaw ignore rules.',
        'Remove OS junk such as .DS_Store and ._* before publishing.',
        'Verify the publish candidate set is clean before commit.',
      ]),
    },
    {
      relativePath: '.opskit/skills/deploy-readiness/SKILL.md',
      content: buildSkillDoc('Deploy Readiness', [
        'Confirm required runtime files exist.',
        'Confirm the service binds to the configured port.',
        'Summarize approval inputs before deployment.',
      ]),
    },
    {
      relativePath: '.opskit/agents/reviewer.md',
      content: buildAgentDoc('Reviewer', [
        'Focus on defects, regressions, and missing verification.',
        'Prefer concise findings over broad commentary.',
      ]),
    },
    {
      relativePath: '.opskit/agents/security.md',
      content: buildAgentDoc('Security', [
        'Flag secrets, unsafe permissions, and risky external actions.',
        'Treat deployment and credential handling as high-risk paths.',
      ]),
    },
    {
      relativePath: '.opskit/agents/release.md',
      content: buildAgentDoc('Release', [
        'Confirm deploy prerequisites are satisfied.',
        'Capture the final status, URL, and operator-facing outcome.',
      ]),
    },
  ];
}

async function pathExists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}

function mergeGitIgnore(existingContent) {
  const existingLines = new Set(
    existingContent
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean)
  );

  const missingLines = BASELINE_GITIGNORE_LINES.filter((line) => !existingLines.has(line));
  if (missingLines.length === 0) {
    return existingContent.endsWith('\n') ? existingContent : `${existingContent}\n`;
  }

  const normalizedExisting =
    existingContent.trim().length === 0
      ? ''
      : existingContent.endsWith('\n')
        ? existingContent
        : `${existingContent}\n`;

  return `${normalizedExisting}${missingLines.join('\n')}\n`;
}

async function walkWorkspaceForJunk(rootPath, currentPath, matches) {
  const entries = await fs.readdir(currentPath, { withFileTypes: true });

  for (const entry of entries) {
    const absolutePath = path.join(currentPath, entry.name);
    const relativePath = path.relative(rootPath, absolutePath);

    if (isIgnoredSegment(entry.name) || shouldIgnoreWorkspaceEntry(relativePath)) {
      matches.push(absolutePath);
      continue;
    }

    if (entry.isDirectory()) {
      await walkWorkspaceForJunk(rootPath, absolutePath, matches);
    }
  }
}

export function shouldIgnoreWorkspaceEntry(relativePath) {
  return splitSegments(relativePath).some(isIgnoredSegment);
}

export function buildBaselineGitIgnore() {
  return `${BASELINE_GITIGNORE_LINES.join('\n')}\n`;
}

export async function ensureBaselineGitIgnore(workspaceRoot) {
  const gitIgnorePath = path.join(workspaceRoot, '.gitignore');
  const existingContent = (await pathExists(gitIgnorePath))
    ? await fs.readFile(gitIgnorePath, 'utf8')
    : '';
  const mergedContent = mergeGitIgnore(existingContent);

  await fs.mkdir(workspaceRoot, { recursive: true });
  await fs.writeFile(gitIgnorePath, mergedContent, 'utf8');

  return gitIgnorePath;
}

export async function seedRepoContract({ workspaceRoot, task }) {
  const files = getRepoContractFiles(task);
  const artifacts = [];

  await fs.mkdir(workspaceRoot, { recursive: true });
  await ensureBaselineGitIgnore(workspaceRoot);
  artifacts.push({
    artifactType: 'file',
    artifactPath: path.join(workspaceRoot, '.gitignore'),
    metadata: { relativePath: '.gitignore' },
  });

  for (const file of files) {
    const absolutePath = path.join(workspaceRoot, file.relativePath);
    await fs.mkdir(path.dirname(absolutePath), { recursive: true });
    await fs.writeFile(absolutePath, file.content, 'utf8');
    artifacts.push({
      artifactType: 'file',
      artifactPath: absolutePath,
      metadata: { relativePath: file.relativePath },
    });
  }

  await removeWorkspaceJunk(workspaceRoot);

  return {
    summary: `Seeded repo contract kit with ${files.length + 1} files`,
    artifacts,
  };
}

export async function collectWorkspaceJunk(workspaceRoot) {
  if (!(await pathExists(workspaceRoot))) {
    return [];
  }

  const matches = [];
  await walkWorkspaceForJunk(workspaceRoot, workspaceRoot, matches);
  return matches.sort((left, right) => right.length - left.length);
}

export async function removeWorkspaceJunk(workspaceRoot) {
  const junkPaths = await collectWorkspaceJunk(workspaceRoot);

  for (const targetPath of junkPaths) {
    await fs.rm(targetPath, { recursive: true, force: true });
  }

  return junkPaths;
}
